### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by dbu** [php-http/HttplugBundle#1]
Initial goal:

* php_http.client => alias to something providing Http\Adapter\HttpAdapter (note that the adapter and client interfaces [are supposed to be merged](https://github.com/php-http/adapter/issues/38)
* php_http.message_factory => alias to something providing Http\Message\MessageFactory
* php_http.uri_factory => alias to something providing Http\Message\UriFactory

If no configuration is given, this bundle provides services using the `::find` as factory methods. This is the zero-config scenario. those could be named php_http.client.default and so on. the default service could be used with a service decorator when several clients are needed.

Alternatively, the user can specify the client (adapter) class / factory class in which case a service instantiating that class directly is created. This would replace the factory service definition and be php_http.client.default as well.

A third option is to specify the service explicitly, allowing to configure clients with custom initialization. In that case, the php_http.client.default can still exist (e.g. as a base for service decorator) but the explicit service is aliased.

**Comment by sagikazarmark** [comment]
Sounds like a good plan. I really like the fallback possibilities.

**Comment by ricbra** [comment]
Great initiative!

**Comment by dbu** [comment]
done in #6
