### ISSUE TITLE
Put sources in src/

### ISSUE THREAD

**Issue by Nyholm** [php-http/HttplugBundle#12]
To be consistent with other php-http repositories I would suggest to put the source files in src/ and tests in tests/. It is already 11 files in the repository root and only one file belongs to the bundle. 

This is bundle which you might want to treat differently, that's why I ask a questions before sending a PR. 

Do you want this change?

**Comment by dbu** [comment]
that would be against symfony best practices. i would prefer to follow
the symfony conventions here. afaik there are no technical reasons that
would prevent us from moving the code into a src/ folder - but i think
its easier to understand following the symfony bundle conventions.

**Comment by Nyholm** [comment]
Okey, I must have missed that in the best practices document. You are right then, we should not put sources in src/
