### ISSUE TITLE
WebProfiler broken when there was a redirect. 

### ISSUE THREAD

**Issue by Nyholm** [php-http/HttplugBundle#121]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Version | ec48ab0340a49dff815f0e17490e8343b896af9a |
#### Actual Behavior

When you are using the redirect plugin and there was a redirect we get a longer request stack and that will break the the profiler page.
#### Steps to Reproduce

Configure a client with some plugins and use the Redirect plugin in the middle of the chain. Then make a call where the server responds with a redirect. Now inspect the request in the web profiler.

**Comment by dbu** [comment]
break as in visually break? or php exception?

**Comment by Nyholm** [comment]
Sorry, PHP exception. 

If we have registered 5 plugins we should have a request stack of length 5. But with the RedirectPlugin we get a longer request stack. So we get an "Array key does not exist"-exception

**Comment by sagikazarmark** [comment]
Should we wait with tagging 1.3.0 until this is resolved?

**Comment by Nyholm** [comment]
I think it is okey to tag 1.3.0. This bug has been present since 1.0 if I recall correctly. The only difference now is that we have documented the bug.

**Comment by sagikazarmark** [comment]
ok

**Comment by asentner** [comment]
Getting the same error with redirection.

```Key "3" for array with keys "0, 1, 2" does not exist in HttplugBundle::webprofiler.html.twig at line 118```

**Comment by fbourigault** [comment]
Any news about this bug?

**Comment by dbu** [comment]
being worked on in #128
