### ISSUE TITLE
There's not always a Stack on the Collector

### ISSUE THREAD

**Issue by dkvk** [php-http/HttplugBundle#133]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 1.4.0

In some cases the call to `getCurrentStack()` on the collector can return `false`. https://github.com/php-http/HttplugBundle/blob/master/Collector/Collector.php#L67-L70
This happens when there has not been any `Stack` added to the `Collector` and `end()` only returns `
false`

This results in a break when it's not taken in consideration here: https://github.com/php-http/HttplugBundle/blob/master/Collector/ProfilePlugin.php#L61

**Comment by sagikazarmark** [comment]
Did we introduce another BC break? 😞

**Comment by dbu** [comment]
sounds more like a regression than a BC break - but we should fix it. @fbourigault can you maybe check on this?

**Comment by fbourigault** [comment]
I know that `Collector::getCurrentStack` could return false, but as long as the `StackPlugin` is the first one, this should not happen. @dkvk how do you configured your client?

**Comment by Nyholm** [comment]
Reopening this since #134 is a non perfect fix

**Comment by fbourigault** [comment]
@dkvk do you have more informations about the client configuration which triggered the error?

**Comment by fbourigault** [comment]
I reproduced the issue. This happens when clients are created with discovery as something was forgotten during profiler internal rewrite. https://github.com/php-http/HttplugBundle/blob/master/DependencyInjection/HttplugExtension.php#L446-L452
