### ISSUE TITLE
investigate hhvm build failure

### ISSUE THREAD

**Issue by dbu** [php-http/HttplugBundle#14]
investigate why hhvm builds fail and fix them. we started ignoring the fail in #11

**Comment by xabbuh** [comment]
Looks like failures are triggered by Puli.

**Comment by sagikazarmark** [comment]
Confirmed, puli does not support HHVM ATM: https://github.com/puli/cli/blob/master/.travis.yml#L22

**Comment by Nyholm** [comment]
Puli is no longer a dependency to this bundle. We should consider rewrite our tests so they are not dependent of Puli.
