### ISSUE TITLE
Make `clients.acme.factory` optional and use discovery instead

### ISSUE THREAD

**Issue by fbourigault** [php-http/HttplugBundle#168]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | N/A

I propose to make the `factory` key of the client configuration optional (`clients.acme.factory`).
In such case, we will use the discovery to find an available implementation. Of course, the `config` node would be disabled when no factory is set.

**Comment by Nyholm** [comment]
I like this one. Do you want to send a PR?

**Comment by fbourigault** [comment]
Yes!
