### ISSUE TITLE
Missing php-http/client-implementation on composer require

### ISSUE THREAD

**Issue by PWalkow** [php-http/HttplugBundle#172]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | latest/any

#### Actual Behavior
On `composer require php-http/httplug-bundle`
    `- php-http/httplug-bundle v1.6.0 requires php-http/client-implementation ^1.0 -> no matching package found.`

#### Possible fix

Require at least one of the client by default, like `php-http/curl-client`
.

#### Steps to Reproduce
On any composer project try to require this bundle

**Comment by Nyholm** [comment]
That composer error message is for you. We do not care **which** client you install. But we do require that you **have one** installed. 

If you want the curl client, please run: 
`composer require php-http/httplug-bundle php-http/curl-client`

If you want Guzzle 6 you may run:
`composer require php-http/httplug-bundle php-http/guzzle6-adapter`

Read more about virtual packages here: http://docs.php-http.org/en/latest/httplug/users.html

**Comment by dbu** [comment]
our README is unfortunate, it does not mention this... will try to fix it.

**Comment by dbu** [comment]
oh, it does mention it actually, but the command line shown still won't work.
