### ISSUE TITLE
Profiling hide original service definition

### ISSUE THREAD

**Issue by fbourigault** [php-http/HttplugBundle#191]
Once decorated, the following plugin no longer have `setAuthorization` method available in the `App\Http\Plugin\AuthorizationPlugin` service because of being decorated with `ProfilePlugin`. To get access to the original plugin, you have to reference it using the `App\Http\Plugin\AuthorizationPlugin.debug.inner` name.

```php
namespace App\Http\Plugin;

use Http\Client\Common\Plugin;
use Psr\Http\Message\RequestInterface;

class AuthorizationPlugin implements Plugin
{
    /**
     * @var string
     */
    private $authorization;

    /**
     * @param string $authorization
     */
    public function setAuthorization($authorization)
    {
        $this->authorization = $authorization;
    }

    /**
     * {@inheritdoc}
     */
    public function handleRequest(RequestInterface $request, callable $next, callable $first)
    {
        if (!$this->authorization) {
            return $next($request);
        }

        return $next($request->withHeader('Authorization', $this->authorization));
    }
}
```
```yaml
App\Http\Plugin\AuthorizationPlugin:
    class: App\Http\Plugin\AuthorizationPlugin
```

The ongoing work with `PluginClientFactory` is supposed to fix this. The only thing to consider is about possible BC break.

**Comment by Nyholm** [comment]
This is a BC break indeed. Could it be solved by magic functions?

**Comment by fbourigault** [comment]
I think it should be solved by not using dependency injection decoration.
