### ISSUE TITLE
Event listener to register adapter/factory with discovery very early

### ISSUE THREAD

**Issue by dbu** [php-http/HttplugBundle#2]
It would make sense to have a request listener that comes very early and registers the adapter or factory as specified. This would be a workaround for libraries that solely depend on discovery and have no injection to override the discovery.

**Comment by sagikazarmark** [comment]
:+1:

**Comment by joelwurtz** [comment]
Why not doing this in a Compiler Pass ? So we would profite of the cache from the builded container and avoid adding a event listener which will be executed at each request.

**Comment by dbu** [comment]
yes, i think compiler pass makes more sense indeed!

**Comment by sagikazarmark** [comment]
We could use the puli discovery directly for this.

**Comment by dbu** [comment]
not sure. the idea was that we configure the discovery thing with the default instances as they are ocnfigured in symfony, so that people *not* using symfony DI but discovery still get the correct client. actually i think the compiler pass does not work for that. but it can be an optional listener that can be disabled (or maybe even explicitly enabled).

does that option even still exist if we use puli? to explicitly *set* the client/factory that will be returned by find()

**Comment by sagikazarmark** [comment]
Ah, I probably missed the idea then.

Well, puli should automatically provide installed clients, so we don't have to keep a central list of them.

**Comment by dbu** [comment]
i am talking about this: https://github.com/php-http/discovery/blob/master/src/ClassDiscovery.php#L18

but i think puli does that different, with the puli.json files, right?

**Comment by sagikazarmark** [comment]
Correct.

**Comment by dbu** [comment]
glad i did not yet work on this then :-)
