### ISSUE TITLE
ProfileClient overrides other feature clients

### ISSUE THREAD

**Issue by Nyholm** [php-http/HttplugBundle#206]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | dev-master

#### Actual Behavior

When HttplugBundle's client "foo" is configured with `HttpMethodsClient`. If "foo" is used in discovery it will be picked up by third party bundles. If that third party bundle uses the new ClientFactory from php-http/common we will get an error [in the `ProfileClient`](https://github.com/php-http/HttplugBundle/blob/master/Collector/ProfileClient.php#L58) since `HttpMethodClient` is not a `HttpClient` AND `HttpAsyncClient`. 

Also, even if `HttpMethodClient` were to implement `HttpClient` and `HttpAsyncClient`, the `ProfileClient` would not implement the features/functions of the `HttpMethodClient`.

We should reconsider if decorating pattern is feasible here. If that is our only option, we should maybe consider using dynamic proxys for creating the `ProfileClient`. I made something like that in the [CacheBundle](https://github.com/php-cache/cache-bundle/pull/75)

-------------

Edit: If we decorate a client with PluginClient we will not expect the functions from MyCustomClient to be available. 

However, the PluginClient must accept an HttpClient **or** an AsyncHttpClient.

**Comment by fbourigault** [comment]
Proxies would also solve https://github.com/php-http/HttplugBundle/issues/91.

**Comment by Nyholm** [comment]
> Also, even if HttpMethodClient were to implement HttpClient and HttpAsyncClient, the ProfileClient would not implement the features/functions of the HttpMethodClient.

This is wrong. Or it is the expected behaviour. We wrap the client in a Plugin client so we should not expect the methods from `HttpMethodsClient` to exist.
