### ISSUE TITLE
ServiceNotFoundException:You have requested a non-existent service "httplug.client"

### ISSUE THREAD

**Issue by develaper** [php-http/HttplugBundle#213]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no

We have been stuck with this problem and I will really appreciate any guidance on how to solve it:
After some tries we managed to have everything working (locally and in production) smoothly with Symfony version 3.1.10 + swiftmailer + MailgunBundle + httplug-bundle + Guzzle 6 Adapter.
But if we try to make a composer update or composer install then we get this error:
` [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]  
  You have requested a non-existent service "httplug.client". `

Here is our require statement of the composer.json file:

`"require":`
` {   `
`"php": ">=5.5.9",`
       ` "symfony/symfony": "3.1.*",`
      `  "doctrine/orm": "^2.5",`
       ` "doctrine/doctrine-bundle": "^1.6",`
      `  "doctrine/doctrine-cache-bundle": "^1.2",`
       ` "symfony/swiftmailer-bundle": "^2.3",`
        `"symfony/monolog-bundle": "^2.8",`
        `"symfony/polyfill-apcu": "^1.0",`
        `"sensio/distribution-bundle": "^5.0",`
        `"sensio/framework-extra-bundle": "^3.0.2",`
        `"incenteev/composer-parameter-handler": "^2.0",`
        `"friendsofsymfony/user-bundle": "~2.0@dev",`
        `"hwi/oauth-bundle": "^0.5.1",`
        `"illuminate/database": "^5.4",`
        `"knplabs/knp-paginator-bundle": "^2.5",`
        `"yceruto/breadcrumbs-bundle": "^1.0",`
        `"cspoo/swiftmailer-mailgun-bundle": "0.4.0",`
        `"php-http/guzzle6-adapter": "^1.1.1",`
        `"php-http/httplug-bundle": "^1.6"`
    `},`

 And here is a part of the config.yml:

httplug:
    plugins:
        logger: ~
    clients:
        acme:
            factory: 'httplug.factory.guzzle6'
            plugins: ['httplug.plugin.logger']
            config:
                verify: false
                timeout: 2

cspoo_swiftmailer_mailgun:
    key: "key-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    domain: "mydomain.net"
    http_client: 'httplug.client' # Optional. Defaults to null and uses dicovery to find client.

    # Swiftmailer Configuration
swiftmailer:
    transport: "mailgun"
    spool:     { type: memory } # This will start sending emails on kernel.terminate event# Swiftmailer Configuration
    #host:      "%mailer_host%"
    #username:  "%mailer_user%"
    #password:  "%mailer_password%"
    #spool:     { type: memory }
    #encryption: "%mailer_encryption%"

To be honest I don't have any clue about what is going on here. I tried to find any conflict between the versions that we are using comparing the composer.lock that was working with the new one but I am not able to find where is the problem. Any tip will be really appreciated.

**Comment by dbu** [comment]
hm, don't see whats up. so just composer install is enough to get the problem? its odd that bin/console cache:clear would not have the same problem as composer install.

to debug, can you disable mailgun and its config, and then dump the services to see what services in the httplug namespace exist?

**Comment by develaper** [comment]
Hey @dbu thanks, I am affraid that I didn't copy paste the whole error message, here is:
`[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]  
  You have requested a non-existent service "httplug.client". `
`Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception`
`[RuntimeException] An error occurred when executing the "'cache:clear --no-warmup'" command: [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]    
    You have requested a non-existent service "httplug.client".    `

After disabling cspoo_swiftmailer_mailgun the output of running `php bin/console debug:container` related to httplug is:
httplug.async_client.default                                                                           Http\Client\HttpAsyncClient                                                                 
  httplug.auto_discovery.auto_discovered_client                                                          Http\Client\Common\PluginClient                                                             
  httplug.client                                                                                         alias for "httplug.client.acme"                                                             
  httplug.client.acme                                                                                    Http\Client\Common\PluginClient                                                             
  httplug.client.default                                                                                 alias for "httplug.client.acme"                                                             
  httplug.message_factory                                                                                alias for "httplug.message_factory.default"                                                 
  httplug.message_factory.default                                                                        Http\Message\MessageFactory                                                                 
  httplug.strategy                                                                                       Http\HttplugBundle\Discovery\ConfiguredClientsStrategy                                      
  httplug.stream_factory                                                                                 alias for "httplug.stream_factory.default"                                                  
  httplug.stream_factory.default                                                                         Http\Message\StreamFactory                                                                  
  httplug.uri_factory                                                                                    alias for "httplug.uri_factory.default"                                                     
  httplug.uri_factory.default                                                                            Http\Message\UriFactory 

After reading here that httplug.client is an alias for "httplug.client.acme" I tried  to use it in the config instead of httplug.client and everything worked fine (I hope). SO now I can proced with composer install or update without any problem.
Before closing the issue I would like to ask here if someone has any idea about what was going on and why the config that previously was working didn't work anymore.

**Comment by fbourigault** [comment]
Could you provide the output of ˋbin/console debug:container httplug.client.acme`,  ˋbin/console debug:container httplug.client.default` and ˋbin/console debug:container httplug.client`?

**Comment by develaper** [comment]
`bin/console debug:container httplug.client.acme`

  Information for Service "httplug.client.acme"
 ------------------      ------------------------------------------------------ 
  Option                 Value                                                 
 ------------------      ------------------------------------------------------ 
  Service ID           httplug.client.acme                                   
  Class                   Http\Client\Common\PluginClient                       
  Tags                   -                                                     
  Public                 yes                                                   
  Synthetic            no                                                    
  Lazy                  no                                                    
  Shared              yes                                                   
  Abstract            no                                                    
  Autowired          no                                                    
  Autowiring Types   -                                                     
  Factory Class      Http\HttplugBundle\ClientFactory\PluginClientFactory  
  Factory Method     createPluginClient                                    
 ------------------ ------------------------------------------------------ `

`bin/console debug:container httplug.client.default`
// This service is an alias for the service httplug.client.acme 

`bin/console debug:container httplug.client`

// This service is an alias for the service httplug.client.acme

**Comment by fbourigault** [comment]
As you are able to debug it, I don't see where is the problem. Is this still an issue to you? Could you provide a reproducer?

**Comment by dbu** [comment]
that is not a service but an alias, defined in : https://github.com/php-http/HttplugBundle/blob/d12c15d9e09c02b6d0e7b04f5f85117e2d582320/DependencyInjection/HttplugExtension.php#L52-L54

in symfony 4, this alias will be private, but unless you do some trickery you can't install this bundle with symfony 4 yet. is there some compiler pass from mailgun or custom that does something with the client, like try to handle it as service instead of alias?

**Comment by dbu** [comment]
fixed in https://github.com/php-http/HttplugBundle/commit/e46804656cc4b4ddde00305adf24e584605f5455
