### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by christophelechevallier** [php-http/HttplugBundle#214]
[RuntimeException]                                                           
  Http\HttplugBundle\Collector\ProfileClient::__construct first argument must  
   implement Http\Client\HttpClient and Http\Client\HttpAsyncClient. Consider  
   using Http\Client\Common\FlexibleHttpClient.

**Comment by fbourigault** [comment]
Could you provide more information (a verbose stack trace and details about how you configured the client)?

**Comment by fbourigault** [comment]
I guess you found what was wrong!
