### ISSUE TITLE
should autodiscovered clients be public or private?

### ISSUE THREAD

**Issue by dbu** [php-http/HttplugBundle#218]
when building with symfony 3.4, we get warnings that we access private services. but at least some of those are [explicitly set to private](https://github.com/php-http/HttplugBundle/blob/542d39d9c03ebd3044f35fbd08fb36cc87fde941/DependencyInjection/HttplugExtension.php#L374). what was the intention of creating those alias but then setting them to private? 

the other failure is on httplug.client - should that not be public? and what about named clients? should they be public or not? imo the plugins and stuff should be private and only handled in DI, but for the clients themselves, they should be public.

@Nyholm and @fbourigault your names show up in git blame on those lines, what do you think? shall i just remove a bunch of `setPublic(false)` calls?

**Comment by fbourigault** [comment]
Those aliases are private as they only exist to wire the `httplug.strategy` service:
https://github.com/php-http/HttplugBundle/blob/542d39d9c03ebd3044f35fbd08fb36cc87fde941/Resources/config/services.xml#L7-L11

**Comment by dbu** [comment]
should we do a unit test instead then, with a mock container? or how should we best test this in the future?

**Comment by fbourigault** [comment]
Adding test to ensure that services are public would help us to avoid BC breaks!

**Comment by Nyholm** [comment]
I think all services should be private. Why would you ever need `$this->contaner->get($service)`?

**Comment by fbourigault** [comment]
For Symfony < 4 compatibility?

**Comment by Nyholm** [comment]
In Symfony <4 they are public by default. In SF4 they are private as default (as they should)

**Comment by Nyholm** [comment]
If we do not specify `public=xx` it would work without any BC break, right?

**Comment by fbourigault** [comment]
Yes! (I already have a similar discussion with @dbu)

**Comment by dbu** [comment]
for the record: agreed to make them private

**Comment by dbu** [comment]
(edited comment, noticed it was confusing)

**Comment by Nyholm** [comment]
Good!
