### ISSUE TITLE
Register on packagist

### ISSUE THREAD

**Issue by egeloen** [php-http/HttplugBundle#22]
It seems this package is not registered on packagist.

**Comment by egeloen** [comment]
I have registered it, feel free to add you as maintainers.

**Comment by sagikazarmark** [comment]
@egeloen please add me (mark.sagikazar) as maintainer.

**Comment by dbu** [comment]
we did not add it right away because it was not ready at all. now it starts becoming usable, so thanks for adding it. can you please add me (dbu) as well?

**Comment by sagikazarmark** [comment]
@dbu Added you as maintainer.
