### ISSUE TITLE
PHP message: PHP Fatal error:  Cannot use Http\Client\Common\PluginClientFactory

### ISSUE THREAD

**Issue by pico34** [php-http/HttplugBundle#234]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 1.8.0

#### Actual Behavior

1.7.1 works, upgrade to 1.8.0 throws an error

 "PHP message: PHP Fatal error:  Cannot use Http\Client\Common\PluginClientFactory as PluginClientFactory because the name is already in use in /var/www/project/vendor/php-http/httplug-bundle/Collector/PluginClientFactoryListener.php on line 5" while reading response header from upstream

PHP 7.0.6

**Comment by fbourigault** [comment]
This is a bug which was fixed in PHP 7.0.7 (http://bugs.php.net/72159). Could you upgrade your PHP version?

**Comment by Nyholm** [comment]
@pico34 What php version are you running?

**Comment by pico34** [comment]
Upgrade from PHP 7.0.6 to 7.0.19 (my prod version) fixes the problem (7.0.7 should fix too, i didn't try)
Thanks @fbourigault
