### ISSUE TITLE
Add support for BaseUriPlugin plugin

### ISSUE THREAD

**Issue by Nyholm** [php-http/HttplugBundle#235]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | next

The [`BaseUriPlugin`](https://github.com/php-http/client-common/blob/v1.6.0/src/Plugin/BaseUriPlugin.php) is not supported by the bundle yet. We should fix that. 

The implementation is very similar to how we do it with `AddHostPlugin` plugin. 

1. First see "AddHostPlugin" [documentation](http://docs.php-http.org/en/latest/integrations/symfony-full-configuration.html). (add_host)
2. Add an entry in [plugins.xml](https://github.com/php-http/HttplugBundle/blob/1.8.0/Resources/config/plugins.xml#L33-L36)
3. Update [Configurations.php](https://github.com/php-http/HttplugBundle/blob/1.8.0/DependencyInjection/Configuration.php#L285-L300)
4. Add the actual [service declaration in the extension class](https://github.com/php-http/HttplugBundle/blob/1.8.0/DependencyInjection/HttplugExtension.php#L199-L207). 

@llaakkkk is that something you want to look into?

**Comment by llaakkkk** [comment]
great opportunity, I will do it!
