### ISSUE TITLE
Improve design of profiler and add support for formatting request/response body

### ISSUE THREAD

**Issue by ostrolucky** [php-http/HttplugBundle#245]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes

Please compare how does profiler look like between these bundles. csa/guzzle-bundle is A LOT clearer.

<table>
<tr><th>csa/guzzle-bundle</th><th>php-http/httplug-bundle</th></tr>
<tr><td><img src="https://user-images.githubusercontent.com/496233/34644966-286466c0-f342-11e7-9f4e-35a4156006b1.png" width="400" alt="csa/guzzle-bundle profiler" /></td>
<td valign="top"><img src="https://user-images.githubusercontent.com/496233/34644977-8c2fe486-f342-11e7-8032-e896f09cf022.png" width="400" alt="php-http/httplug-bundle profiler"  /></td>
</tr>
</table>

I suggest:
1. Syntax highlight json responses (even better, xml too)
1. Don't put request/response side-by-side
1. Use table for headers
  

edit: Syntax highlighting/formatting might look like a hard part. It isn't, look at referenced bundle. [Detection and formatting](https://github.com/csarrazi/CsaGuzzleBundle/blob/2.x/src/Twig/Extension/GuzzleExtension.php#L38-L65), syntax highlight is done by [prismjs](http://prismjs.com/)

**Comment by dbu** [comment]
+1 for headers as table. syntax highlighting could indeed be cheap with some js library. the side-by-side could also be a responsive layout to switch below a certain screen size.

do you want to start with a pull request for headers in a table? that sounds the most quickwin to me.

for syntax highlighting, i am +1 even though it means bundling some js library to do that.

**Comment by fbourigault** [comment]
Request and response are displayed side by side because when you toggle the plugin execution, you can read starting from the left going down each plugin change in the request and then go up on the right side to see how plugins modify the response. Also, syntax highlighting would be great but be careful as the content may be truncated depending on the body length captured while profiling.

**Comment by dbu** [comment]
> Request and response are displayed side by side because when you toggle the plugin execution, you can read starting from the left ...

ah right. wdyt about having the csa bundle layout first, but once you activate the plugin display, it switches to our current side-by-side layout? maybe additionally responsive so that on really large screens, we always get side by side?

**Comment by fbourigault** [comment]
Yes, we could have a different layout for the main display.

**Comment by ostrolucky** [comment]
I'm not frontend developer. If you don't want to get rid of vertically split layout, classical tables might not be best fit. For instance, in posted screenshot one of the header keys is very long. 

![2szwodw8je](https://user-images.githubusercontent.com/496233/34650689-6e69d8d4-f3c5-11e7-99da-307faf423fbd.png)


Using classical tables would mean first column will be as wide as largest element is, which would leave very little space for second column. Of course, you can prevent that by setting max-width for first column, but now you are mixing there static variables, that's not good. One obvious reason why - it will also mean if all content of all keys is small, first column will still take unnecessary width.

So this should be built properly by someone who is better in frontend than me. I believe using flexbox?

**Comment by dbu** [comment]
i guess we would have to do a maxwidth on both columns of the table and shorten too long headers (in css). if you have a designer who wants to work on it, please do...

**Comment by dbu** [comment]
fixed in #355

**Comment by ostrolucky** [comment]
Not really, only partially. Syntax highlighting of JSON body is missing.

**Comment by dbu** [comment]
oh, right. i consider that an optional thing - if you want to contribute it, please do, but i don't think we need an open issue until you (or someone else) wants to pick it up and add the feature.
