### ISSUE TITLE
upgrade to phpunit 6

### ISSUE THREAD

**Issue by dbu** [php-http/HttplugBundle#248]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | master (next minor release)

Upgrade to phpunit 6 and drop support for too old versions of PHP. While doing that, also refactor the `@expectedException` annotations to $this->expectException() calls.

**Comment by fbourigault** [comment]
If the only reason to drop older PHP version is the `@expectedException` annotation, I would like to wait for something bigger.

**Comment by dbu** [comment]
i guess it would also allow us to do other cleanups. but agreed, its not urgent.

**Comment by dbu** [comment]
we did this at some point last year, closing this issue
