### ISSUE TITLE
Inline profiler styles and scripts

### ISSUE THREAD

**Issue by norkunas** [php-http/HttplugBundle#250]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | master

#### Actual Behavior

Without using `assets:install` httplug section scripts and styles are not loaded.

#### Expected Behavior

Styles and scripts should be loaded properly.

#### Steps to Reproduce

Remove all installed assets from this bundle and open profiler.

#### Possible Solutions

Those files could be created as twig templates and just included like symfony does:
```{{ include('@WebProfiler/Profiler/profiler.css.twig') }}```

**Comment by Nyholm** [comment]
Great suggestion. I've added a PR
