### ISSUE TITLE
Issues with debug toolbar

### ISSUE THREAD

**Issue by antonmedv** [php-http/HttplugBundle#253]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 1.6 4655962c64e2de96c418caf576c57215711c7877

#### Actual Behavior

<img width="3346" alt="2018-02-11 20 45 54 redacted" src="https://user-images.githubusercontent.com/141232/36074034-b64604ee-0f6c-11e8-8bc9-62e2ded8208c.png">

#### Expected Behavior
Nice CSS

**Comment by Nyholm** [comment]
Thank you for this issue. 

I would assume it is related to https://github.com/php-http/HttplugBundle/pull/251. Could you confirm that?

**Comment by antonmedv** [comment]
How to check it?

**Comment by Nyholm** [comment]
Are you using 1.6, 1.8.1 or dev-master?

**Comment by Nyholm** [comment]
Or maybe you are using an older version and did not run `asset:install`? Try and see if `"php-http/httplug-bundle": "dev-master"` will work better.

**Comment by antonmedv** [comment]
"php-http/guzzle6-adapter": "^1.1",
"php-http/httplug-bundle": "^1.8",

assets:install font helped. I'm using only

**Comment by fbourigault** [comment]
Could you try with dev-master? We inlined javascript/css code to match Symfony behavior.

**Comment by antonmedv** [comment]
If it inlines - then ok. Thanks for awesome project!
