### ISSUE TITLE
Add support for ContentTypePlugin

### ISSUE THREAD

**Issue by nesl247** [php-http/HttplugBundle#258]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | 1.10.0

#### Actual Behavior

`Unrecognized option &quot;content_type&quot; under &quot;httplug.clients.optOut.plugins.3&quot;`

#### Expected Behavior

`httplug.plugin.content_type` should work.

#### Steps to Reproduce

Use `httplug.plugin.content_type` as a plugin.

#### Possible Solutions

Add support for the ContentTypePlugin.

P.S. Is there a reason that all plugins have to be explicitly known by the bundle?

**Comment by dbu** [comment]
hi @nesl247 
to start with your question: each plugin has its specific class name and configuration. if we want to configure plugins, the bundle needs to know them. however, you can set the client to use any plugin by specifying the service name. i will try to improve the doc at http://docs.php-http.org/en/latest/integrations/symfony-bundle.html#plugins to be more explicit about this.

imo we should indeed support all plugins from httplug/client-common, so the content type plugin is indeed missing. do you want to do a pull request to add support for it?

**Comment by nesl247** [comment]
@dbu I had meant more like why does it need a service instead of translating `content_type` into `ContentTypePlugin` and instantiating that with default values. I would imagine that if the name does not match a Symfony service, it would fallback to such behavior.

As far as supporting all plugins, I agree. I will look into adding support for the ContentTypePlugin.

**Comment by dbu** [comment]
some plugins make sense without arguments, others don't. i prefer not to add some magic to translate something_whatever to SomethingWhateverPlugin and see if that can be instantiated. we should try to remember to add support in the bundle when a plugin is added in the client-common package.

thanks for doing that pull request for content type.

for every other purpose, a custom service needs to be used anyways as we can't use the plugin namespace. with autowiring, you can basically just specify class names if you have custom plugins without constructor arguments.
