### ISSUE TITLE
format the request and response body

### ISSUE THREAD

**Issue by perentti** [php-http/HttplugBundle#260]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | Last Version

#### Actual Behavior

The actual toglgle body

{"query":"query($type: String, $query: Json!, $first: Int, $offset: Int) {\n search {\n documents(type: $type, query: $query, first: $first, offset: $offset)\n }\n }","variables":{"type":"item","query":"[]","first":30,"offset":0}}

#### Expected Behavior

It is possible to improove the current dump body  when we click on toggle body buton.
I just want to have the good format of the json query and response dump. like this:

{
   "query": "query($type: String, $query: Json!, $first: Int, $offset: Int) {\n search {\n documents(type: $type, query: $query, first: $first, offset: $offset)\n }\n }",
   "variables": {
      "type": "item",
      "query": [],
      "first": 30,
      "offset": 0
   }
}

#### Steps to Reproduce
Before the request and after the response
#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

**Comment by Nyholm** [comment]
This might be a good idea if we discover it is "well formatted json". That is not always the case since it might be truncated. 

I think we can try to format the body just before we display it... or maybe in the data collector.

**Comment by dbu** [comment]
i would not alter the body in the data collector. but i would guess there are js libraries that can format json (and xml) and also offer collapsing parts of the data. we could try to detect if such a formatter can handle the body and if so, offer a button to activate that formatter.

**Comment by perentti** [comment]
Yes of course, it could be an option also the goal is to have some good display for reading easy. 
xml format could be necessary too.

**Comment by Nyholm** [comment]
I meant that the data collector could store both `body` and `body_formatted`. But it might be best to keep "view stuff" in the actual view. 

@perentti could you investigate this further and make a PR?

**Comment by dbu** [comment]
> I meant that the data collector could store both body and body_formatted. But it might be best to keep "view stuff" in the actual view.

i think its better to do it in the view. otherwise we duplicate memory footprint. plus a nice javascript tool might do more than just format: interactive collapsing, color highlighting, ...

though not sure how well those things can cope with truncated data - and we do need to truncate the body to not use up too much memory...

looking forward to ideas from @perentti :+1:

**Comment by dbu** [comment]
the profiler has been reworked and looks quite nice now
