### ISSUE TITLE
PHP-CS-Fixer not working anymore

### ISSUE THREAD

**Issue by Soullivaneuh** [php-http/HttplugBundle#266]
It seems you remove my abandoned styleci-config-bridge package. But the `.php_cs` file still use it.

Would you like me to configure [FlintCI](https://flintci.io/) service? It will allow you to have your common configuration on `.php_cs` only, this service will only run it without any extra configuration except the activation itself.

Regards.

**Comment by Nyholm** [comment]
If I remember correctly, it was removed because it did not work properly. (I might be wrong). 
We are running style CI now and we keep the .php_cs up-to-date with our styleCI config. 

What extra features would FlintCI give?

**Comment by Soullivaneuh** [comment]
> We are running style CI now and we keep the .php_cs up-to-date with our styleCI config.

The issue is my bridge would not be maintained anymore because StyleCI didn't follow the new configuration of php-cs-fixer-v2, making the things impossible to do on my side.

I decide to make FlintCI to just run the tool without having to configure it elsewhere than the `.php_cs` file. So you have only one config, no bridge anymore and anyone can run it with ease on cli local.
It also provide support for other linters/fixers.

You can of course keep StyleCI, but I recommend to not use my bridge anymore if you want up to date fixers list.
