### ISSUE TITLE
Interface suffix

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/HttplugBundle#28]
I know it's kind of Symfony standard, but does it really make sense?

**Comment by Nyholm** [comment]
I believe it is a PSR standard from the beginning. But I believe we should follow every Symfony best practice for public bundles. 

:+1:

**Comment by sagikazarmark** [comment]
No, it is NOT PSR. Everyone believes that it is, but it isn't. It is an INTERNAL bylaw for the FIG, but thank god, it hasn't been standardized.

Symfony supports this Interface suffix practice in fact, but so far, I haven't been convinced that it is good, quite the opposite acually.

My most linked blog post by @mathiasverraes: http://verraes.net/2013/09/sensible-interfaces/

**Comment by Nyholm** [comment]
> No, it is NOT PSR. Everyone believes that it is, but it isn't. It is an INTERNAL bylaw for the FIG, but thank god, it hasn't been standardized.

Sorry, I miss-spoke. It is not a coding standard but as you say, PHP-fig apply `Interface` and `Trait` suffix and Abstract prefix. 

Thank you for the link.

**Comment by dbu** [comment]
not sure why fig is doing the suffixes. its indeed common throughout symfony, but in php-http we don't do it and i see the reasons not to do the suffixes. i don't mind much either way. we can change it if people think that is better.

**Comment by sagikazarmark** [comment]
I don't insist on this one. If we decide to follow symfony standards, let's keep the suffix. If not, drop it.

**Comment by dbu** [comment]
i really don't know which is better / less confusing.

**Comment by joelwurtz** [comment]
I think it's more a matter of: should we be consistent for the dependencies, or on the organisation itself ?

For me i would like to keep the same rules across php-http packages, but i don't mind having Interface or not in the name, only detail to my eyes.

**Comment by Nyholm** [comment]
@joelwurtz makes a great point. Lets be coherent with php-http.

**Comment by dbu** [comment]
okay. who does the pull request?

**Comment by sagikazarmark** [comment]
I will in the evening.
