### ISSUE TITLE
Remove Twig dependency

### ISSUE THREAD

**Issue by ruudk** [php-http/HttplugBundle#300]
I just discovered that HTTPlugBundle requires Twig. I guess the only need for this is because of the HTTP profiler extension. Wouldn't it be an idea to remove the Twig dependency, and only register the HTTP profiler when Twig is enabled?

**Comment by dbu** [comment]
right, we should not require that but move it to suggest and require-dev.

i would not fiddle around with not registering if no twig is available, but add a check in https://github.com/php-http/HttplugBundle/blob/f94de3b2548c9f7499092dbf4eeaefe890a22ff3/DependencyInjection/Configuration.php#L130 to explode if we end up enabling the profiler but twig is not available, and throw an exception explaining that you need to install twig or disable the profiler.

do you want to do a pull request for that?

**Comment by xabbuh** [comment]
I think using the profiler in a test will work just fine without Twig. The only use case were we need Twig seems to be the `HttpMessageMarkupExtension` which is used in the templates inside the web debug toolbar. So if I don't miss anything we can simply remove that service when Twig is missing (and even that might not be required as the service is private and should be removed automatically by the container during compilation).

**Comment by ruudk** [comment]
Created a PR > https://github.com/php-http/HttplugBundle/pull/302
