### ISSUE TITLE
Installation under Symfony 4.2 not possible

### ISSUE THREAD

**Issue by andydandy80** [php-http/HttplugBundle#307]
Installation under Symfony 4.2.x not possible, after entering command "composer require php-http/httplug-bundle" composer says:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for php-http/httplug-bundle ^1.14 -> satisfiable by php-http/httplug-bundle[1.14.0].
    - php-http/httplug-bundle 1.14.0 requires php-http/cache-plugin ^1.6 -> satisfiable by php-http/cache-plugin[1.6.x-dev] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by dbu** [comment]
hm, i notice that https://github.com/php-http/cache-plugin 1.6 is not released. if you are testing if things would work, could you report if all works fine if you require `php-http/cache-plugin: dev-master as 1.6.0`? i think we can tag the cache-plugin...

**Comment by andydandy80** [comment]
Yes, the version is the problem, it works with your suggestion

**Comment by okyselov** [comment]
Symfony 4.2.2 I've got another error:

```
composer require php-http/httplug-bundle
Using version ^1.14 for php-http/httplug-bundle          
./composer.json has been updated
Loading composer repositories with package information                                                                                                  Updating dependencies (including require-dev)         Restricting packages listed in "symfony/symfony" to "4.2.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for php-http/httplug-bundle ^1.14 -> satisfiable by php-http/httplug-bundle[1.14.0].
    - php-http/httplug-bundle 1.14.0 requires php-http/client-implementation ^1.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

```

**Comment by beberlei** [comment]
I have this fail for me too, with 1.14 (stable) depending on logger-plugin 1.11, which is not stable yet.

**Comment by dbu** [comment]
@okyselov you also need a client implementation for httplug bundle. if you use flex, you can `composer require http` to install the bundle along with the curl-client. if you prefer a different client, you can e.g. use `composer require php-http/httplug-bundle php-http/guzzle6-adapter`. a list of clients is at http://docs.php-http.org/en/latest/clients.html (though not all have been released for httplug 2 yet).

logger plugin 1.11 does not exist. we are about to do [1.1](https://github.com/php-http/logger-plugin/pull/10). @beberlei is that a typo or do we depend on logger-plugin 1.11 somewhere?

**Comment by Nyholm** [comment]
Does it work better now?

**Comment by dbu** [comment]
this seems to work now. i tested:

```bash
composer create-project symfony/website-skeleton sf42
cd sf42
composer require php-http/httplug-bundle guzzle6-adapter
```

and end up with

```
psr/http-client (1.0.0)
php-http/httplug (v2.0.0)
php-http/guzzle6-adapter (v2.0.1)
```

the flex recipe is still on httplug 1, but that is a different topic.
