### ISSUE TITLE
Why do we need the cache plugin?

### ISSUE THREAD

**Issue by Nyholm** [php-http/HttplugBundle#310]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      |  dev-master

I did a quick search, Why do we need the cache plugin in our require-section?

**Comment by dbu** [comment]
i wondered the same but did not search...

i suggest we drop it and add a check the configuration class to detect if the class is not available when the plugin is enabled, to tell the user that from now on they need to require the plugin separately if they want it. its a bit of a borderline maybe BC break but not really, imho. with the config check it should be detected unless people run composer update in prod...

**Comment by xabbuh** [comment]
sounds reasonable to me
