### ISSUE TITLE
Next Major: Make classes final where possible

### ISSUE THREAD

**Issue by dbu** [php-http/HttplugBundle#317]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | BC breaking change: Next major

Classes like the factories are not final. We should go over the bundle and make everything final that is not explicitly intended to be extended. Also check for things with `protected` visibility and make them private where possible.

**Comment by xabbuh** [comment]
For one of the next 1.x releases we can already flag these classes with the `@final` annotation in the class docblock. The `DebugClassLoader` from the Symfony Debug component will then raise a deprecation if someone extends these final classes without a hard break.

**Comment by andrew-demb** [comment]
Since there's no final decision from the `@php-http/owners` on the discussion https://github.com/php-http/HttplugBundle/pull/321#issuecomment-559033872 - should this issue be considered to be a blocker for `2.0.0`?

@dbu

**Comment by xabbuh** [comment]
fixed in #467
