### ISSUE TITLE
Release 1.15.0

### ISSUE THREAD

**Issue by Nyholm** [php-http/HttplugBundle#324]
There are quite a few changes in master. We should consider a release. 

@vudaltsov is the change log accurate?

**Comment by vudaltsov** [comment]
@Nyholm , at least https://github.com/php-http/HttplugBundle/pull/305 is not mentioned. I will do my best to submit a PR in the evening and see if anything else is missing.
Thanx for the issue!

**Comment by Nyholm** [comment]
That would be great if you could complete the change log. Thank you!

**Comment by dbu** [comment]
if somebody wants to wrap up #319 or #321 that would be cool. its not a blocker however. i won't have time in the next couple of days and don't want to delay the release if there are relevant things that should be released.

**Comment by ruudk** [comment]
@dbu Would be great to just release what's in master now, as using HTTPlug 2.0 is impossible now because of https://github.com/php-http/HttplugBundle/pull/305.

**Comment by dbu** [comment]
i merged the changelog update and tagged the release. thanks to all who helped!
