### ISSUE TITLE
v1.15.0 breaks cache clearing

### ISSUE THREAD

**Issue by PhilETaylor** [php-http/HttplugBundle#329]
| Q            | A
| ------------ | ---
| Bug?         |yes
| New Feature? | no
| Version      | 1.15.0

PHP Version: 7.3.3
Symfony Version: 4.2.4

#### Actual Behavior

What is the actual behavior?

composer update installed 1.15.0 whereas 1.14.0 was there before, then red error message of

```
Warning: file_get_contents(/var/www/current/vendor/php-http/httplug-bundle/Resources/views/webprofiler.html.twig): failed to open stream: No such file or directory
```

This is caused by changes in 1.15.0, proved by downgrading again to 1.14.0

#### Expected Behavior

What is the behavior you expect?

Cache clears with no errors, like it does with 1.14.0

#### Steps to Reproduce

<img width="1503" alt="Screenshot 2019-04-01 at 13 16 19" src="https://user-images.githubusercontent.com/400092/55327021-0bfaa200-5481-11e9-9e02-967e36296b02.png">

**Comment by dbu** [comment]
that file does exist in 1.15.0 https://github.com/php-http/HttplugBundle/tree/1.15.0/src/Resources/views

i also checked the .zip and .tar.gz files. can you check if the file really is not there in the filesystem or if somehow your system did not pick it up. 

the path to the file looks odd, i'd expected a src somewhere there. we moved files into src/ and test/ between 1.14 and 1.15. can you try deleting var/cache right before running the composer update? maybe something is confused with that?

**Comment by PhilETaylor** [comment]
Before a composer update (1.14.0 installed)
<img width="318" alt="Screenshot 2019-04-01 at 13 57 58" src="https://user-images.githubusercontent.com/400092/55329303-2be09480-5486-11e9-9bf4-769b0cd0780d.png">

running composer update (note there is no **src** in the path!): 

<img width="1496" alt="Screenshot 2019-04-01 at 13 59 23" src="https://user-images.githubusercontent.com/400092/55329399-5df1f680-5486-11e9-863e-9fd5539f4f7d.png">

<img width="321" alt="Screenshot 2019-04-01 at 13 59 36" src="https://user-images.githubusercontent.com/400092/55329429-72ce8a00-5486-11e9-8758-b24d8748eced.png">

**Comment by PhilETaylor** [comment]
seems like symfony flex is not correctly clearing the cache after composer update... 

if I then manually clear the symfony cache (with the symfon cache:clear command) everything is fine... 

I dont think this is a httplug issue after all... I'll debug further and raise an issue upstream.

**Comment by dbu** [comment]
yep, looks like. glad if you can find out where it needs to be fix, i think this has hit me in the past too...

**Comment by robob4him** [comment]
@PhilETaylor is there anything you found out? Any related issues?

**Comment by PhilETaylor** [comment]
I was unable to get to the bottom of this, sorry.

**Comment by dbu** [comment]
@robob4him i think the issue really is that symfony or flex chokes up when directories move on such an update when the templates were already cached. if you want to follow up on it, please open an issue at symfony/flex or symfony/symfony as its not a bug of httplug.
