### ISSUE TITLE
[Symfony 4.3] Update EventDispatcher

### ISSUE THREAD

**Issue by ruudk** [php-http/HttplugBundle#337]
https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching

**Comment by dbu** [comment]
can we do that while keeping BC for users of this bundle and staying compatible with symfony 4.2? or is this a future task for when we move to symfony 5 support?

the parameter reordering only works with 4.3+, and changing our event names is a BC break for consumers of the bundle. are there other changes that we can already do now?

**Comment by ruudk** [comment]
I have no idea how to handle this. Can't we detect the version of `event-dispatcher` that is installed?

**Comment by ruudk** [comment]
Maybe we can use the `LegacyEventDispatcherProxy` https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching#supporting-both-dispatchers

**Comment by ruudk** [comment]
I wonder if we even have to change anything, and can just allow Symfony / Event Dispatcher 4.3? I don't see any call to `dispatch` in the codebase.

**Comment by dbu** [comment]
there is one call in a test that i fixed with a version compare in #340 . i think that should actually solve this warning. please reopen if you encounter it still with current master.
