### ISSUE TITLE
Incompatibility with php-http/curl-client 2.x

### ISSUE THREAD

**Issue by deguif** [php-http/HttplugBundle#338]
| Q            | A
| ------------ | ---
| Bug?         | yes
| Version      | 1.15.2

#### Actual Behavior

Not compatible with `php-http/curl-client` 2.0 as the Curl client expects a `Psr\Http\Message\ResponseFactoryInterface` and a `Psr\Http\Message\StreamFactoryInterface` arguments, but the `CurlFactory` instantiates the curl client with a `Http\Message\MessageFactory` and a `Http\Message\StreamFactory`.

#### Possible Solutions

Change the type-hint in the curl factory but this would probably be a BC break.

**Comment by dbu** [comment]
thanks, yep we are aware of this issue. for now, you can restrict the curl client to 1.* to avoid the issue. somebody is looking at doing a pull request to support curl-client 2.*.

**Comment by deguif** [comment]
Thanks @dbu for the info and sorry for the noise.

**Comment by dbu** [comment]
no worries, thanks for reporting the issue. it was not visible in github that we are aware of the problem, no mistake from you at all, on the contrary, glad when people report issues so we are aware of them ;-)

**Comment by deguif** [comment]
Thanks @dbu 
Will a new release be published?

**Comment by dbu** [comment]
yes, sure. i am preparing the release now.

**Comment by deguif** [comment]
Thanks again @dbu for the release
