### ISSUE TITLE
Async request not visible in the profiler

### ISSUE THREAD

**Issue by mathroc** [php-http/HttplugBundle#352]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 1.16.0

#### Actual Behavior

when async request qre made they don't appear in the profiler

#### Expected Behavior

I'd like to see the async request made on the page. If the request did not finish I should still see the request and be able to understand that it was an async request and that the response was still pending

#### Steps to Reproduce

browse to a page making async request and open the profiler

**Comment by ostrolucky** [comment]
This already works
![image](https://user-images.githubusercontent.com/496233/136699336-145a3f71-1d21-4fd6-aeba-310fba374683.png)
