### ISSUE TITLE
Conflict with twig 3.0 / symfony 4.4

### ISSUE THREAD

**Issue by CodeDuck42** [php-http/HttplugBundle#358]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | N/A

#### Actual Behavior

composer install stops

#### Expected Behavior

it should work just fine

#### Steps to Reproduce

- upgrade a project to symfony 4.4 (+symfony/twig-bundle)
- install httplug-bundle

#### Possible Solutions

- use twig namespaced file names
- or forbid installation of twig 3.0

**Comment by xabbuh** [comment]
What errors did you get when trying to install the bundle?

**Comment by dbu** [comment]
we never did a release with the new templating and the extension relies on the non-namespaced twig classes.... fixing in #359 and if that one is good, i will tag a release with all the improvements we did to the panel.
