### ISSUE TITLE
Xdebug nested issue

### ISSUE THREAD

**Issue by Webonaute** [php-http/HttplugBundle#386]
**PHP version**: x.y.z (hint: `php --version`)
php 7.4
HttplugBundle : versions : * 1.18.0

**Description**

When running xdebug code coverage, lots of my test failing because of this nesting more than 256 time.
  
/home/travis/build/<project>/vendor/php-http/httplug-bundle/src/Collector/ProfileClient.php:134
/home/travis/build/<project>/vendor/php-http/client-common/src/VersionBridgeClient.php:22
/home/travis/build/<project>/vendor/php-http/httplug-bundle/src/Collector/ProfileClient.php:134
/home/travis/build/<project>/vendor/php-http/client-common/src/VersionBridgeClient.php:22
/home/travis/build/<project>/vendor/php-http/httplug-bundle/src/Collector/ProfileClient.php:134
/home/travis/build/<project>/vendor/php-http/client-common/src/VersionBridgeClient.php:22
/home/travis/build/<project>/vendor/php-http/httplug-bundle/src/Collector/ProfileClient.php:134
/home/travis/build/<project>/vendor/php-http/client-common/src/VersionBridgeClient.php:22
/home/travis/build/<project>/vendor/php-http/httplug-bundle/src/Collector/ProfileClient.php:134

any idea could point me to a solution?

I would prefer a solution that is not increasing max nested level of xdebug.

**Comment by dbu** [comment]
maybe you can turn of profiling when running the test suite? other than that, i don't have an easy solution other than increasing the nesting level configuration. 

if you want to look into the profiling mechanism and see if we can reduce the nesting level, please do, but i don't know if it is possible.
