### ISSUE TITLE
Do we need a dependency injection tag?

### ISSUE THREAD

**Issue by Nyholm** [php-http/HttplugBundle#39]
When I use this bundle I starting to convert services that were previously dependent on Guzzle or that used the auto discovery. With this bundle I can inject the `httplug.client` and `httplug.message_factory`. I tend to write services that looks like this: 

```php
<?php

namespace Acme\CoreBundle\Service;

use Http\Client\HttpClient;
use Http\Message\MessageFactory;

/** 
 * A service that send data to the statistics server
 */
class StatisticsClient
{
    /**
     * @var string
     */
    private $apiUrl;

    /**
     * @var HttpClient
     */
    private $client;

    /**
     * @var MessageFactory
     */
    private $messageFactory;

    /**
     *
     * @param string $apiUrl
     * @param HttpClient $client
     * @param MessageFactory $messageFactory
     */
    public function __construct(HttpClient $client, MessageFactory $messageFactory, $apiUrl)
    {
        $this->apiUrl = $apiUrl;
        $this->client = $client;
        $this->messageFactory = $messageFactory;
    }

    /**
     * @param array  $data
     */
    public function post(array $data)
    {
        // do some logic on $data

        $request = $this->messageFactory->createRequest('POST', $this->apiUrl, [], json_encode($data));
        $this->client->sendRequest($request);
    }
}
```

All of them depends on `httplug.client` and `httplug.message_factory`. Im will add a dependency injection tag and a trait in my application to easily do a setter injection on services like this. 
Question: Is that something that should live in the bundle?

Suggestion on tag name: `httplug`
Traits: `ClientAccessorTrait`, `MessageFactoryAccessorTrait`, `StreamFactoryAccessorTrait`, `UrlFactoryAccessorTrait`. All of them have a getter and setter for a private property. 

EDIT: 

Or maybe just one trait and one tag that will inject the  `httplug.client` and `httplug.message_factory` only. Please correct me if I'm wrong but those will be the most used services. 
Btw, this suggestion is all about developer experience.

**Comment by sagikazarmark** [comment]
Well, I don't know. Adding a setter to your service instead of using a trait (or creating a trait inside your application) and adding setter injection to your service definition doesn't sound to be a big deal.

Are there any similar stuff for logger for example?

**Comment by xabbuh** [comment]
The MonologBundle does something like that for the [monolog.logger tag](https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/Compiler/LoggerChannelPass.php). But in my opinion that is a bit special as it not only injects the logger but chooses the right one based on the configured channel. As far as I can see there is nothing requiring comparable complex logic here which justifies usage of a tag instead of letting the user inject what they need.

**Comment by dbu** [comment]
i think adding a tag is about as much effort for the user as adding the httplug client service directly as an argument. so there is no added value. or am i missing something?

regarding traits, i would like to avoid promoting setter injection for this. logger is a special case as it can be seen as optional. the client is most likely not optional so it should not be possible to instantiate a service without a client => constructor injection.

**Comment by sagikazarmark** [comment]
Sorry, it just fits here:

http://ocramius.github.io/extremely-defensive-php/#/53

:stuck_out_tongue:

**Comment by Nyholm** [comment]
That is a great presentation. 

I just wanted to mention the idea. I'll do it in my application instead.

**Comment by dbu** [comment]
yep, that was one of the talks i saw.

there is people arguing even a logger must be injected as NullLogger or
whatever, so its never optional. but imho that is debatable. but for an
integral part of the system like the http client in an api client class,
setter injection feels just wrong.

**Comment by joelwurtz** [comment]
Also since there is the `wired` feature on symfony it will work withtout tag / specifying a service ?

**Comment by sagikazarmark** [comment]
@Nyholm one more thing about traits: it is probably not a good idea to use private properties in traits, especially in such general case. You have no insights about where those traits might be used. In case of inheritance, private properties cannot be accessed by child classes, so in this case protected would be better.
