### ISSUE TITLE
investigate what other things we could port from IvoryHttpAdapterBundle

### ISSUE THREAD

**Issue by dbu** [php-http/HttplugBundle#4]
https://github.com/egeloen/IvoryHttpAdapterBundle

**Comment by sagikazarmark** [comment]
I can't really see any more stuff which we don't have.

**Comment by dbu** [comment]
@Nyholm anything you think we miss? otherwise i propose we close this. we can always add more stuff if we realize we need more.

**Comment by Nyholm** [comment]
The IveryHttpAdapterBundle has this concept of global and local configuration. Which means that you can say "All my adapters should have this plugin". I do not think that is necessary and in only makes the bundle more complex. 

They do also dispatch symfony events when requests are sent and errors. Our way of doing injecting such functionality is by a plugin. 

The only thing, as far as I can see, that IveryHttpAdapterBundle does better is their WebProfile page. But we have tickets for that.

**Comment by dbu** [comment]
> The only thing, as far as I can see, that IveryHttpAdapterBundle does
> better is their WebProfile page. But we have tickets for that.

yeah, i think people can write their own glue plugin for that, instead
of writing a symfony event handler. one layer of glue sounds enough :-)
