### ISSUE TITLE
Remove discovery dependency, rely on puli directly

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/HttplugBundle#40]
Discovery is a static, convenience wrapper around Puli discovery. Instead of using discovery as factories for services, we should use Puli discovery service to find resources at compile time (if that's possible at all).

This would have two side-effects:

- If puli discovery is used at compile time, then container compilation will fail if no resource is found (message factory, etc). IMO this is good, because the earlier we know something is bad the better it is
- We won't get the same NotFound exception

WDYT?

**Comment by dbu** [comment]
agreed. did you want to do a PR for that?

**Comment by sagikazarmark** [comment]
Yeah, I wanted, but I didn't have the time. Go for it if you have.

**Comment by dbu** [comment]
no time on this end, sorry. i fear we have to wait for a stable puli
release anyways, so there is no massive hurry. would be good to know a
roadmap for puli however...

**Comment by webmozart** [comment]
@dbu @sagikazarmark The original goal was to release a first stable release by end of 2015. Unfortunately, we failed to achieve that. Our plan is to simplify Puli in order to prepare it for a final release. I hope we can do it by mid 2016.

**Comment by sagikazarmark** [comment]
Thanks for the info @webmozart

**Comment by sagikazarmark** [comment]
Hm, further thinking about it: I think we should refactor the discovery layer as well. Currently the whole discovery layer is static. We could make the discovery layer itself non-static to accept a Puli discovery instance.

But we need static, so we can add another layer around discovery which gets the puli factory and injects the Puli discovery into our discovery layer.

Basically I would do the same non-static thing inside the bundle. This way we have it in the discover (allowed to be reused with pure Puli), we have the static layer, and we reuse the code in the bundle as well.

**Comment by dbu** [comment]
should we consider this a blocker for the 1.0 release or do we go with what we have and get this out? i would prefer releasing now - there is a lot of refactoring involved and puli itself is not released as stable yet anyways - so likely we have to adapt things again anyways and do a 2.0 release later this year.

**Comment by sagikazarmark** [comment]
Well, I am fine with that. However, currently discovery is actually used in this package. I would still prefer rewritting it's usage in this bundle so that we can remove the discovery dependency and use directly the puli discovery service provided by the puli bundle.
