### ISSUE TITLE
The collector formatter needs to implement Http\Message\Formatter::formatResponseForRequest

### ISSUE THREAD

**Issue by stof** [php-http/HttplugBundle#412]
**PHP version**: any

**Description**
A new `Http\Message\Formatter::formatResponseForRequest` has been soft-introduced in the Formatter interface in php-http/message 1.13.0 (see https://github.com/php-http/message/releases/tag/1.13.0).
Currently, the bundle triggers a deprecation warning due to not implementing the method.

**How to reproduce**

**Possible Solution**
Implement the new method in the formatter.

**Additional context**

**Comment by dbu** [comment]
thanks for reporting @stof , i am fixing it in #413
