### ISSUE TITLE
"message":"User Deprecated: Class \"Nyholm\\Psr7\\Factory\\HttplugFactory\" is deprecated since version 1.8, use \"Nyholm\\Psr7\\Factory\\Psr17Factory\"

### ISSUE THREAD

**Issue by dobrianskyi** [php-http/HttplugBundle#455]
Hi,
In Symfony 6.4 when I use your bundle and when I warm up cache (php bin/console cache:warmup --env=dev) I get this deprecation

{"message":"User Deprecated: Class \"Nyholm\\Psr7\\Factory\\HttplugFactory\" is deprecated since version 1.8, use \"Nyholm\\Psr7\\Factory\\Psr17Factory\" instead.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: Class \"Nyholm\\Psr7\\Factory\\HttplugFactory\" is deprecated since version 1.8, use \"Nyholm\\Psr7\\Factory\\Psr17Factory\" instead.","code":0,"file":"/app/vendor/nyholm/psr7/src/Factory/HttplugFactory.php:18"}},"level":200,"level_name":"INFO","channel":"php","datetime":"2024-05-27T08:36:06.221991+00:00","extra":{"token":{"xray_current_trace_id":"aaa55696e2fba16b","xray_root_trace_id":"1-665445f6-45975a8ad9dd0bd84cb718c3","app_version":"dev","server":"unknown","mem_usage":24751248,"command":"debug:container"}}}

Ther is closed issue in discovery lib https://github.com/php-http/discovery/issues/260 
please use Psr17FactoryDiscovery instead of the [also deprecated](https://github.com/php-http/discovery/blob/1.x/src/MessageFactoryDiscovery.php#L13) MessageFactoryDiscovery

But you use MessageFactoryDiscovery in vendor/php-http/httplug-bundle/src/Resources/config/services.xml:26

could you please help me fix this deprecation. 

Thanks

**Comment by dbu** [comment]
the services are still in this bundle to avoid BC breaks.

but they will only be used if you ask for `httplug.message_factory` or `Http\Message\MessageFactory`.

you should instead have your code ask for `httplug.psr17_request_factory` / `Psr\Http\Message\RequestFactoryInterface` (or depending on what you need for response, stream, uri, uploaded_file, server_request).
