### ISSUE TITLE
deprecate old guzzle bundles

### ISSUE THREAD

**Issue by dbu** [php-http/HttplugBundle#5]
talk to the maintainers of the [tons of guzzle bundles](https://packagist.org/search/?q=guzzle%20bundle) and see if they can contribute to this bundle instead and deprecate their bundles.

**Comment by sagikazarmark** [comment]
Good luck with that. :wink: (I admit this is probably not the input you wanted :stuck_out_tongue_winking_eye: )

**Comment by dbu** [comment]
well, we at least have to try ;-)

@sagikazarmark in our projects, we usually inject a service with guzzle pre-configured to a domain, possible with basic auth, a user agent or some other extra headers. is that possible in a generic way with the php-http client/adapter infrastructure or does that require knowing the specific client being used?

**Comment by sagikazarmark** [comment]
It is/will be possible. Ivory Http Adapter supported BasicAuth using an event-driven logic. In PHP HTTP there will be a plugin system (middleware or pipeling) to allow that.

The following two plugins are work in progress:

- https://github.com/php-http/authentication
- https://github.com/php-http/cookie

Basically you will be able to build pipelines which will be able to alter requests before sending it. Currently my plan is to implement the main plugin class as a PsrHttpClient decorator.

**Comment by sagikazarmark** [comment]
Based on the various community feedback, our first job is to prove that using an abstration is better than sticking to a client. After that, we can reach out Guzzle bundle maintainers as well.

**Comment by joelwurtz** [comment]
For me it's quite simple, we have to offer features that are not available in Guzzle or other clients, and after we just say : Respect the HttpClient interface with ONE method `sendRequest` and you can profit of all the features offered by php-http : 

Plugins (Cache, Handling big file with low memory footprint, Compression, ....), Discovery, Framework Integration, Batch, ...

The set of features offered by php-http by just respecting only one interface with one method is really nice IMO, by increasing the set of features we tell them, yes all of this is available despite the client you choose, and despite what the future may offer in term of http client)
