### ISSUE TITLE
Documentation: Use for Reusable Bundles

### ISSUE THREAD

**Issue by Nyholm** [php-http/HttplugBundle#58]
The current documentation says: 

> Use for Reusable Bundles
> Rather than code against specific HTTP clients, you want to use the Httplug `Client` interface. To avoid building your own infrastructure to define services for the client, simply `require: php-http/httplug-bundle` in your bundles `composer.json`. You SHOULD provide configuration for each of your services that needs an HTTP client to specify the service to use, defaulting to `httplug.client`. This way, the default case needs no additional configuration for your users.
> The only steps they need is `require` one of the adapter implementations in their projects `composer.json` and instantiating the HttplugBundle in their kernel.

Is this really the best practice? If a third party bundle define `httplug.client` in their services.yml it will be very difficult to change the client used. I've done like [this](https://github.com/Happyr/TranslationBundle#default-configuration) time to time but it does not feel 100% perfect. It is a lot to write for the third party bundle but it works perfectly. 

Can I get some feedback? Does it exists any other options?

**Comment by sagikazarmark** [comment]
I think there is one thing which makes this harder: testing. You cannot unit test your extension if there is external config in it.

I also met this problem with php-cache/adapter-bundle: One of my reusable bundle services required a cache instance. What I did was using the provider as an argument in my service, which required to define the configuration in the application. I don't know if it is better or not.

I think in our case (and in adapter-bundle after all) it is not a problem to rely on a client with a unique name. But in that case the bundle MUST make it clear that this configuration is required in order to work.

Another possibility is what you suggest, I don't know if one is better than the other. Better mention both.

**Comment by sagikazarmark** [comment]
Is this resolved? Or leave it after stable?

**Comment by Nyholm** [comment]
I wanted to have some discussion or reasoning about how to document. We can tag a stable release with this issue open. I will make sure to close this issue this week.

**Comment by sagikazarmark** [comment]
:+1:

**Comment by dbu** [comment]
i think i wrote that paragraph :-) maybe its just misunderstanding. my idea was:

* allow to configure the client service
* default it to the default client provided by FOSHttpCacheBundle

not overwrite that service, that would be indeed a very bad idea. maybe we could add that if you need a specifically configured client, you could provide your own service (in your own namespace) and default to that name instead

**Comment by fbourigault** [comment]
When 3rd party use the discovery to create clients, we are able to display their output in the profiler. Once #154 is merged, low level client information will be collected (informations collected by `StackPlugin` and `ProfileClient`). We don't have plugin details (see #109).

Today, you have two levels of possible integration, the first one is for a library which let the user do all the thing by hand:

```yaml
services:
    my_client:
        class: Http\Client\HttpClient #don't know if an interface works here
        factory: ['Http\Discovery\HttpClientDiscovery', find]
    third_party_service:
        class: ...
        arguments: ['@my_client']
```

This is a bit verbose and I think the  DX can be improved.

A library like `knplabs/github-api` provides a `Builder` which configure all the stack as required (with ability to override all the config). In such case, you just have to:

```yaml
services:
    github:
        class: Github\Client
```

This approach is really DX friendly and doesn't require php-http knowledge. The Symfony integration documentation could be only the above snipet plus a recommendation for HttplugBundle to have profiling.

IMHO, we should encourage 3rd party libraries to build their client like done in `knplabs/github-api`.

WDYT?

**Comment by dbu** [comment]
this is covered by https://github.com/php-http/documentation/issues/210
