### ISSUE TITLE
Todos before stable

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/HttplugBundle#64]
- [x] Make PluginClientFactory final
- [x] Fix PluginClientFactory constructr docblock (array of Plugins)
- [x] Update changelog
- [x] Update README title: "Symfony integration for HTTPlug"

**Comment by Nyholm** [comment]
:+1:

**Comment by Nyholm** [comment]
We do also need to deal with these: 
* https://github.com/php-http/HttplugBundle/blob/master/HttplugFactory.php#L83
* https://github.com/php-http/HttplugBundle/blob/master/HttplugFactory.php#L83
