### ISSUE TITLE
Add support for clients in client-common

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/HttplugBundle#70]
For example methods client

**Comment by Nyholm** [comment]
We got the current clients: 

* [ ] BatchClient
* [x] PluginClient (added with configuration)
* [x] HttpMethodsClient
* [x] FlexibleClient
* [x] EmulatedHttpClient (by FlexibleClient)
* [x] EmulatedHttpAsyncClient (by FlexibleClient)

Should we support BachClient as well?

**Comment by dbu** [comment]
it sounds useful to have the batch client. i think there are use cases to want to send whole batches of requests.

**Comment by Nyholm** [comment]
Okey. I'll try to manage a PR with that as well.

**Comment by Nyholm** [comment]
Ive submitted a PR for the BatchClient as well. PR #103 will close this ticket.
