### ISSUE TITLE
Guzzle 6 Factory does not respect our defaults for a Guzzle client

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/HttplugBundle#74]
https://github.com/php-http/guzzle6-adapter/blob/master/src/Client.php#L30

**Comment by sagikazarmark** [comment]
Maybe we could add a named constructor to our guzzle adapter, like `createWithConfig` and handle this case there. WDYT?

**Comment by dbu** [comment]
not sure i understand. the linked client creates a custom stack to have guzzle not use all of its defaults to be consistent with the other clients. if you explicitly give it a client however, it just uses that.

what defaults are we missing?

**Comment by sagikazarmark** [comment]
These: https://github.com/php-http/guzzle6-adapter/blob/master/src/Client.php#L31-L33

We agreed to use these defaults in order to remove request error handling from guzzle.

**Comment by dbu** [comment]
ah, i see now. the problem is with https://github.com/php-http/HttplugBundle/blob/master/ClientFactory/Guzzle6Factory.php#L22

how can we pass the configuration to the guzzle? should we build our handler stack and then array_merge the $config with ['handler' => $handlerStack]?

**Comment by sagikazarmark** [comment]
I guess that would be a good option, yes. If anyone wants to create a client from scratch, still can. So sticking to our defaults in the factory is a viable option IMO.

**Comment by sagikazarmark** [comment]
Or that's another option:

https://github.com/php-http/HttplugBundle/issues/74#issuecomment-217147216

**Comment by dbu** [comment]
that would be nice indeed. its sort of a mini-BC break on the bundle side to no longer use guzzle default behaviours, but i would say adding that to the changelog is good enough.

**Comment by dbu** [comment]
i will do some PRs

**Comment by dbu** [comment]
https://github.com/php-http/guzzle6-adapter/pull/31
