### ISSUE TITLE
Integrate with Symfony Debug Timeline

### ISSUE THREAD

**Issue by Nyholm** [php-http/HttplugBundle#92]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | n/a

Looking at @csarrazi's [Guzzle Bundle](https://github.com/csarrazi/CsaGuzzleBundle) they have a really nice integration with the Symfony Debug timeline. That is something we should support as well.

**Comment by joelwurtz** [comment]
Isn't this only adding the StopwatchPlugin ?

**Comment by Nyholm** [comment]
True
