### ISSUE TITLE
Update design on WebProfiler

### ISSUE THREAD

**Issue by Nyholm** [php-http/HttplugBundle#93]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | yes |
| Version | n/a |

Our WebProfiler has just been updated with much more information and new design. But there is room for improvements. If we look at @florianpreusner's [Guzzle Bundle](https://github.com/8p/GuzzleBundle) we see some nice screenshots of how it could look like.

**Comment by sagikazarmark** [comment]
Doesn't it use the builtin VarDumper? To be honest I am not sure if representing eg. headers as a php data structure is the best we can do.

**Comment by fbourigault** [comment]
@csarrazi's [Guzzle Bundle](https://github.com/csarrazi/CsaGuzzleBundle) show us nice screenshots too.

I will start updating the design by introducing Symfony 2.8+ badges count in the toolbar and the menu.

As the 2.7 and 2.8 are really different, what do you think about doing first a small refactoring to avoid writing everywhere `{% if constant('Symfony\\Component\\HttpKernel\\Kernel::VERSION_ID') >= 20800 %}`! I propose to create 3 templates files:
- `webprofiler.html.twig` which would be the 2.8+ profiler design.
- `webprofiler_legacy.html.twig` which would be the 2.7 profiler design.
- `webprofiler_common.html.twig` which would be the shared design.
With those 3 templates and the extensive use of blocks, updating the design would be easier.

The right design would be picked by the DI Extension which would set the `template` tag attribute to the right one.

WDYT?

**Comment by dbu** [comment]
another option would be to bump the minimal symfony version to 2.8. that is no big jump from 2.7 and will simplify the work here... any objections to that?

**Comment by fbourigault** [comment]
Would be even better! But does this require a new major release?

**Comment by dbu** [comment]
imho no. composer.json will make sure it does not get accidentally installed. it should be a new minor version though, so that we can still release bugfixes for 2.7 if somebody really needs one. 1.4 is not yet released, so that would be fine.

**Comment by fbourigault** [comment]
If everybody agrees, I can do the cleanup and bump the requirement to 2.8+.

**Comment by Nyholm** [comment]
I agree. Bump it to 2.8 =)

**Comment by fbourigault** [comment]
For the next improvement, what do you think to have one small line per request and having to click to expand this request?

It would be something like https://github.com/8p/GuzzleBundle and in later improvements, we will be able to push badges on the right like a curl formater button, stopwatch informations, etc..

Once this done, we could improve the per-request inner display.

WDYT?

**Comment by Nyholm** [comment]
Sound good

**Comment by fbourigault** [comment]
Here is a wireframe about what I have in mind for the profiler. The 2nd block is what is displayed when you click on the `>`. The 3rd block is what is displayed when you click on the `Show stack` button.

![httplugbundle](https://cloud.githubusercontent.com/assets/1116116/24630369/afea4800-18bc-11e7-8019-61f913a270d0.jpg)

I also added cURL button (#108), and the request timing (#135).

**Comment by dbu** [comment]
this is extremely cool, thanks for your efforts! lets make this happen.

**Comment by fbourigault** [comment]
@Nyholm if you agree with the layout, I will start working on it to build a functional prototype and then apply styles.

**Comment by Nyholm** [comment]
I do really like it. Please, go ahead. Im happy to review you PR

**Comment by stof** [comment]
you should not use the constant to detect the version of the profiler design (btw, the HttpKernel 2.8 is compatible with WebProfilerBundle 2.7 and so with the old design. Too bad when using a separate package for version detection...). You should use the builtin WebProfilerBundle feature to choose the design version (see in doctrineBundle for instance)

**Comment by stof** [comment]
this would mean having a single template though

**Comment by fbourigault** [comment]
We already merged the 2.7 drop. It's easier to style with only one profiler as we can rely on 2.8+ CSS styles. It's also easier to develop as you don't have to switch between 2.7 and 2.8. If someone really need to upgrade the bundle, he could also upgrade Symfony to 2.8!

**Comment by fbourigault** [comment]
Could we close this issue since #146 is merged?

**Comment by Nyholm** [comment]
Yes! Thank you
