### ISSUE TITLE
Rename toolbar config to profiling

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/HttplugBundle#99]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | 2.0.0

#### Actual Behavior

Currently we have the config called `toolbar`.

#### Expected Behavior

`profiling` seems to be a common standard to me. See symfony and DoctrineBundle.

This could be done supporting BC in the next minor, then remove `toolbar` in the next major.

**Comment by dbu** [comment]
:+1: 

we can simply have a beforeValidation in the Configuration class that moves toolbar to profiling if the old name was used.

**Comment by sagikazarmark** [comment]
You mean beforeNormalization?

**Comment by sagikazarmark** [comment]
I was thinking about that too, but the current toolbar config already has a beforeNormalization part (to allow BC with the auto value). In the new section I would rather not allow that, so in profiling, we should have a simple boolean node without normalization. So I was thinking if it is easier if we just "merge" the configs in the extension. We don't use it anywhere else either. WDYT?

**Comment by dbu** [comment]
oh, indeed i meant beforeNormalization, sorry

BC merging operations should happen in the configuration class imho.
when you do beforeNormalization on top level, you can change anything
you want so we don't need to keep the old nodes around, afaik.

**Comment by sagikazarmark** [comment]
That's what I started to do now, let's see what comes out of it.
